version: '3.8'

services:
  postgres:
    env_file:
      - .env.dev
    image: postgres:15-alpine
    container_name: keepless-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=greenlight
      - POSTGRES_USER=greenlight
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend


  api:
    env_file:
      - .env.dev
    build:
      context: .
      dockerfile: Dockerfile
    
    container_name: keepless-${ENV}
    restart: unless-stopped
    environment:
      - GREENLIGHT_DB_DSN=${GREENLIGHT_DB_DSN}
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - backend
    volumes:
      - ./:/app
    command: ["go", "run", "./cmd/api"]

volumes:
  postgres_data:

networks:
  backend:
