version: '3.8'

services:
  api:
    env_file:
      - .env.stage
    image: keepless-api:latest
    container_name: keepless-${ENV}
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8001:8080"
