version: '3.8'

services:
  api:
    env_file:
      - .env.prod
    image: keepless-api:latest
    container_name: keepless-stage
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8001:8080"
